<div>
    <h1 class="page-header"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Reportes</h1>
    <div class="panel panel-default">
        <div class="panel-body">
             lista de reportes  a | b | c | d |
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            aqui va el detalle de los reportes
        </div>
    </div>

</div>